### PR TITLE
Migration fixes for CleverRaven#50203

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
None

#### Purpose of change
These are the changes needed for all the migration to work correctly in #50203
I'm PRing them here half so you know what I'm doing, and half so I have something to point at for the other half of a PR I'm making adding support for the migrations I specify here.

#### Describe the solution
Replace everything `nato_assault_rifle` with correct new items. Adjust old migrations to migrate to the new rifles, and add new migrations to migrate from the old generic rifle to the new ones.

### CODE REVIEW

**Review by NotDucc — APPROVED** [review]
looked through it, thanks for catching that stuff! Only thing that catches my eye is that the SIG 552 (or the SIG 553 now) was never in Krav Maga to begin with, which I would think would be part of that style. Not sure if that was intentionally removed at one point though

**Comment by anothersimulacrum** [comment]
Yeah, I am not sure. I think it's fine in and am too lazy to check.

**Comment by NotDucc** [comment]
So should I merge this with the branch I made? Been in draft so I'm not sure

**Comment by anothersimulacrum** [comment]
It's in draft so you can't merge it. When the PR enabling it is merged, I'll undraft it and let you know.

**Comment by NotDucc** [comment]
Ah ok, just wanted to check

**Comment by anothersimulacrum** [comment]
Should me ready to merge.

**Pull request merged**
